#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
lockKeyboard;
###########  END HEADER  ###########

# Stuff here

# Run the next script
# nextScript 'https://suckaaa.com/s/script-name-here';

sleep 3s;

setPosition 0 0;
bigMsg 'Hi.';

sleep 3s;

echo "Bye.";

killingInTheNameOf 'Terminal';

#
