#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

bigMsg 'Do I have your attention?!?!';

sleep 5s;

echo 'GOOD!';

echo '\n\n\n';

sleep 3s;

nextScript 'https://suckaaa.com/s/minimize-all-windows';

sleep 6s;
