#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

sleep 1s;

bigMsg "Hah!! Just Kidding!! I mean, I could do it but I won't";

sleep 3s;

# Run the next script
nextScript 'https://suckaaa.com/s/do-i-have-your-attention';
