#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

termdo() {
    osascript -e 'tell application "Terminal" to do script "'"$1"'"'
}

setPosition() {
    printf "\e[3;$1;$2t";
}

setSize() {
    # Fills the screen
    # printf "\e[9;1t";
    printf "\e[$1;$2t";
}

setSizeByChars() {
    # Set the window to $1x$2 characters
    # Note that height characters are much taller than width characters are wide
    # You can make an almost square of screenspace including the terminal window chrome with setWindow 58 28
    # You can make an almost square window with setWindow 58 24
    printf "\e[8;$2;$1t"
}

setFontSize() {
    # Note window 1 is the current window
    osascript -e "tell application \"Terminal\" to set the font size of window 1 to $1"
}

bringToFront() {
    # Bring window to the front
    printf '\e[5t';
}

bold() {
    printf "\e[1m$1\e[0m"
}

italic() {
    printf "\e[3m$1\e[0m";
}

boldItalic() {
    printf "\e[3m\e[1m$1\e[0m";
}

underline() {
    printf "\e[4m$1\e[0m";
}

random() {
    echo $RANDOM;
}

# Doesn't appear to work
# strikethrough() {
#     printf "\e[9m$1\e[0m";
# }

red() {
    printf "\e[31m$1\e[0m";
}

differentRed() {
    printf "\x1B[31m$1\e[0m";
}

makeGoldAndUnderline() {
    printf "\e[3;4;33m$1\n\e[0m";
}

dim() {
    printf "\e[2m$1\e[22m";
}

highlight() {
    printf "\e[4:2m$1\e[4:0m";
}

goldHighlight() {
    printf "\e[4:3m$1\e[4:0m";
}

blink() {
    printf "\e[5m$1\e[25m";
}

invisibleCopyPastable() {
    printf "\e[8m$1\e[28m";
}

turquoise() {
    printf "\e[38;5;42m$1\e[39m";
}

cyanBg() {
    printf "\e[46m$1\e[49m";
}

brightCyanBg() {
    printf "\e[106m$1\e[49m";
}

prompt() {
    read -p "Would you like to proceed with $1 y/n?" -n 1 -r;
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        open https://www.youtube.com/watch?v=BEG-ly9tQGk&feature=youtu.be
    fi
}

# Utils

# This important func, 'run', helps compose bash funcs together.
# It also helps writing code nicer. At my current understanding level,
# this func helps at any time you would previously write '$(...)'
# — now you can use 'run' to not have to think about it.
# Plz share any thoughts you have about any of this

# Here's a before and after example:
# Before — "sleep $(random);"
# After — "sleep run random;"

# If you want to pass multiple args, you can.
# "sleep run randomRange 1 10;"

# Note that "$@" here is acting like spreading the '...args' to a js function
# Here's a JS equivalent of 'run':
# const run = (func, ...args) => {
#
#     return func(...args);
# }
# <3
run() {
    $1 "$@";
}

bigMsg() {
    # It takes work to manage how many newlines
    # should be there for which font size
    clear && setFontSize 120 && bold "\n\n\n$1\n\n\n";
}

animate() {

    $fps = 30;

    $func = $1
    $fromA = $2;
    $fromB = $3;
    $toA = $4;
    $toB = $5;
    $time = $6;

    #
}

animatePosition() {

    $fps = 30;

    $fromA = $2;
    $fromB = $3;
    $toA = $4;
    $toB = $5;
    $time = $6;
}
