#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

# Set the window to 100x50 characters:
printf '\e[8;50;100t'

# Minimize the window for a few seconds, then restore it
printf '\e[2t' && sleep 3 && printf '\e[1t';

# Move the window to the top/left corner of the display
printf '\e[3;0;0t';

# Increase window to size of screen
printf '\e[9;1t'

# Bring window to the front
printf '\e[5t'

# Testing some echo stuff
echo -e "\e[1mbold\e[0m"
echo -e "\e[3mitalic\e[0m"
echo -e "\e[3m\e[1mbold italic\e[0m"
echo -e "\e[4munderline\e[0m"
echo -e "\e[9mstrikethrough\e[0m"
echo -e "\e[31mHello World\e[0m"
echo -e "\x1B[31mHello World\e[0m"
# Bold and underline
printf "\e[3;4;33mthis is a test\n\e[0m"

echo "\nYou actually ran this script!!!\n";

echo "loL";
sleep 1;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 1s;
echo "loL";
sleep 0.1s;
echo "loL";
sleep 0.2s;
echo "loL";

echo "\n";
