#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

echo "loL";
sleep 1;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 5s;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 0.2s;
echo "loL";

echo "\nYou actually ran this!!!";

# printf '\e[2t' && sleep 3 && printf '\e[1t'
