#!/bin/bash

# loL whatcha lookin for in here???
# Don't worry about it!!!

# Set the window to 100x50 characters:
printf '\e[8;50;100t'

# Move the window to the top/left corner of the display
printf '\e[3;0;0t';

# Increase window to size of screen
printf '\e[9;1t'

# Bring window to the front
printf '\e[5t'

# Testing some echo stuff
printf "\e[1mbold\e[0m"
printf "\e[3mitalic\e[0m"
printf "\e[3m\e[1mbold italic\e[0m"
printf "\e[4munderline\e[0m"
printf "\e[9mstrikethrough\e[0m"
printf "\e[31mHello World\e[0m"
printf "\x1B[31mHello World\e[0m"
# Bold and underline
printf "\e[3;4;33mthis is a test\n\e[0m"

# More experiments
printf '\e[1mbold\e[22m'
printf '\e[2mdim\e[22m'
printf '\e[3mitalic\e[23m'
printf '\e[4munderline\e[24m'
printf '\e[4:1mthis is also underline (new in 0.52)\e[4:0m'
printf '\e[21mdouble underline (new in 0.52)\e[24m'
printf '\e[4:2mthis is also double underline (new in 0.52)\e[4:0m'
printf '\e[4:3mcurly underline (new in 0.52)\e[4:0m'
printf '\e[5mblink (new in 0.52)\e[25m'
printf '\e[7mreverse\e[27m'
printf '\e[8minvisible\e[28m <- invisible (but copy-pasteable)'
printf '\e[9mstrikethrough\e[29m'
printf '\e[53moverline (new in 0.52)\e[55m'

printf '\e[31mred\e[39m'
printf '\e[91mbright red\e[39m'
printf '\e[38:5:42m256-color, de jure standard (ITU-T T.416)\e[39m'
printf '\e[38;5;42m256-color, de facto standard (commonly used)\e[39m'
printf '\e[38:2::240:143:104mtruecolor, de jure standard (ITU-T T.416) (new in 0.52)\e[39m'
printf '\e[38:2:240:143:104mtruecolor, rarely used incorrect format (might be removed at some point)\e[39m'
printf '\e[38;2;240;143;104mtruecolor, de facto standard (commonly used)\e[39m'

printf '\e[46mcyan background\e[49m'
printf '\e[106mbright cyan background\e[49m'
printf '\e[48:5:42m256-color background, de jure standard (ITU-T T.416)\e[49m'
printf '\e[48;5;42m256-color background, de facto standard (commonly used)\e[49m'
printf '\e[48:2::240:143:104mtruecolor background, de jure standard (ITU-T T.416) (new in 0.52)\e[49m'
printf '\e[48:2:240:143:104mtruecolor background, rarely used incorrect format (might be removed at some point)\e[49m'
printf '\e[48;2;240;143;104mtruecolor background, de facto standard (commonly used)\e[49m'

printf '\e[21m\e[58:5:42m256-color underline (new in 0.52)\e[59m\e[24m'
printf '\e[21m\e[58;5;42m256-color underline (new in 0.52)\e[59m\e[24m'
printf '\e[4:3m\e[58:2::240:143:104mtruecolor underline (new in 0.52) (*)\e[59m\e[4:0m'
printf '\e[4:3m\e[58:2:240:143:104mtruecolor underline (new in 0.52) (might be removed at some point) (*)\e[59m\e[4:0m'


echo "\nYou actually ran this script!!!\n";

echo "loL";
sleep 1;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 0.2s;
echo "loL";
sleep 1s;
echo "loL";
sleep 0.1s;
echo "loL";
sleep 0.2s;
echo "loL";

echo "\n";
