#!/bin/bash

# Note this script requires you to already have
# the app running on pm2 with name $APP_NAME

# Enforce env vars
if [[ -z "$APP_NAME" ]]; then
    echo "Error: Must specify APP_NAME" 1>&2;
    exit 1;
fi

if [[ -z "$PORT" ]]; then
    echo "Error: Must specify PORT" 1>&2;
    exit 1;
fi

echo "Launching '${APP_NAME}'";

# Move to app folder
cd "/app/${APP_NAME}";

# Some heavy lifting
git pull;
npm ci;
if [[ -d "/app/${APP_NAME}/lib/migrations" ]]; then
    knex migrate:latest;
fi

# pm2
# '--update-env' ensures the env vars set above are good to
# override any existing settings for the new app launch
pm2 restart $APP_NAME --update-env;

# pm2 logs;
